# Generated by Django 5.2.7 on 2025-11-11 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Surveylyze_app', '0003_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSection',
            fields=[
                ('class_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=50)),
                ('year_level', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='student',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='last_name',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='middle_name',
            new_name='middlename',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='last_name',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='middle_name',
            new_name='middlename',
        ),
        migrations.AddField(
            model_name='student',
            name='class_section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='Surveylyze_app.classsection'),
            preserve_default=False,
        ),
    ]
