# Generated by Django 5.2.7 on 2025-11-12 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Surveylyze_app', '0006_remove_teacher_password_teacher_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='date_created',
            new_name='created_date',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='id',
        ),
        migrations.AddField(
            model_name='survey',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='survey',
            name='survey_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='survey',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='Surveylyze_app.teacher'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='survey',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
