# Generated by Django 5.2.7 on 2025-11-13 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Surveylyze_app', '0007_rename_date_created_survey_created_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('likert', 'Likert Scale'), ('short_answer', 'Short Answer')], max_length=20)),
                ('order_number', models.PositiveIntegerField(default=1)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='Surveylyze_app.survey')),
            ],
        ),
    ]
