# Generated by Django 5.2.7 on 2025-11-13 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Surveylyze_app', '0008_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyAssignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_assignments', to='Surveylyze_app.classsection')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='Surveylyze_app.survey')),
            ],
        ),
    ]
