# Generated by Django 5.2.7 on 2025-11-13 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Surveylyze_app', '0009_surveyassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('option_id', models.AutoField(primary_key=True, serialize=False)),
                ('option_text', models.CharField(max_length=255)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='Surveylyze_app.question')),
            ],
        ),
    ]
