# Generated by Django 5.2.7 on 2025-11-15 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Surveylyze_app', '0010_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_attempts', to='Surveylyze_app.student')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_records', to='Surveylyze_app.survey')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('choice_id', models.IntegerField(blank=True, null=True)),
                ('likert_value', models.IntegerField(blank=True, null=True)),
                ('shortanswer_text', models.TextField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='Surveylyze_app.question')),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='Surveylyze_app.surveyhistory')),
            ],
        ),
    ]
