# Generated by Django 5.2.7 on 2025-11-15 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Surveylyze_app', '0011_surveyhistory_studentanswer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surveyhistory',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AlterUniqueTogether(
            name='surveyhistory',
            unique_together={('survey', 'student')},
        ),
        migrations.AlterModelTable(
            name='surveyhistory',
            table='survey_history',
        ),
    ]
