# Generated by Django 5.2.7 on 2025-11-15 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Surveylyze_app', '0012_alter_surveyhistory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='surveyhistory',
            table=None,
        ),
    ]
