# Generated by Django 5.2.7 on 2025-11-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Surveylyze_app', '0014_teacher_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
